### ISSUE TITLE
Sonoma breaks symlinks

### ISSUE THREAD

**Issue by spuder** [Pilaton/MacSync#14]
Thanks for making this app. 

As a long time user of [Ira/Mackup](https://github.com/lra/mackup), I'm looking for a replacement since OSX Sonoma sandboxing [broke symlink support](https://github.com/lra/mackup/issues/1924)

The readme suggests that MacSync also uses symlinks. I suspect it will be susceptible to the same security limitation. 

Can you confirm if symlinks are an essential part of this application, and if Sonoma Breaks MacSync?

**Comment by Pilaton** [comment]
Wow. I use sync all the time and this is the first time I've heard of the symlink issue. 

Yes, MacSync uses symlinks, but I have no problems with them even on Sonoma. 

I'll try to find out why there might be a symlink problem. But most likely the problem is related to the storage location of the original configuration files.

**Comment by spuder** [comment]
Thanks, in hindsight, I should have just looked at the code before opening an issue. I can see that it creates symlinks. 

To clarify, individual files and folders still work as symlinks (`.ssh/config`, `.npmrc`, `.vimrc`), however most applications that save data in `~/Library/Application Support/*.plist` will not work if the plist files are symlinks anymore. Symlinking plist files does not appear to be a primary use case for MacSync.
